"""add x509_certificate_pem and signature_images

Revision ID: 8402dbf35105
Revises: adbd1adbe866
Create Date: 2026-09-30 12:38:42.924623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8402dbf35105'
down_revision = 'adbd1adbe866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signature_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_image', sa.LargeBinary(), nullable=False),
    sa.Column('image_mime', sa.String(length=30), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signature_id'], ['signatures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signature_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_images_signature_id'), ['signature_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x509_certificate_pem', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('x509_certificate_pem')

    with op.batch_alter_table('signature_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_images_signature_id'))

    op.drop_table('signature_images')
    # ### end Alembic commands ###
