"""Add must change password flag

Revision ID: 921d14f21022
Revises: a6dfb981f702
Create Date: 2026-09-26 19:02:00.624710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921d14f21022'
down_revision = 'a6dfb981f702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
